### ISSUE TITLE
Add ability to register facets

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/elasticsearch-extensions#2]
# User Story

> As a developer, I want a programmatic way to register facets that is separate from implementation-specific methods tied to a plugin (e.g., WordPress VIP Enterprise Search) so I can more easily register search facets on my site.

# Acceptance Criteria

* Provide an implementation-neutral method for registering facets via a hook.
* Implement facet registration for the WordPress VIP Enterprise Search adapter, which was created in #1.

**Comment by jakewrfoster** [comment]
I believe this is close as per #7

**Comment by kevinfodness** [comment]
Yep, all set
