### ISSUE TITLE
Add PHP Compatibility Checks for Version 8.1 and 8.2

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/elasticsearch-extensions#5]
# User Story

> As a developer, I want to ensure that Elasticsearch Extensions is compatible with all currently supported versions of PHP.

# Acceptance Criteria

- Ensure that Elasticsearch Extensions declares support for PHP 8.1 and 8.2 in composer.json
- Ensure that it states a required minimum of PHP 8.1 in the plugin's metadata
- Ensure that PHPUnit tests are run against PHP 8.1 and 8.2
- Ensure that phpcs compatibility checks are set to check against PHP 8.1, 8.2

**Comment by moraleida** [comment]
@kevinfodness this is ready for review. Please notice that to get all AC we needed to bump the minimum PHP version to 8.1 and the minimum WP version to 6.2. Let me know if you want to discuss the approaches.

**Comment by moraleida** [comment]
I addressed the changes in the PR and this is ready for review again.
