### ISSUE TITLE
Document hooks in the wiki

### ISSUE THREAD

**Issue by jakewrfoster** [alleyinteractive/elasticsearch-extensions#6]
## Overview
[As per this line in the README](https://github.com/alleyinteractive/elasticsearch-extensions/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20), all filters should be documented in the wiki.
This may be done in the course of writing the adapters, but there is no harm done by adding it as an issue to serve as a reminder.

**Comment by kevinfodness** [comment]
I added them to the README. Do we want to move them to the wiki? I'm on the fence about it, myself.

**Comment by kevinfodness** [comment]
I ended up adding it to the wiki and linking it from the README.
